import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { pipelineData, stageDefaults } from "./data";

interface PDFOptions {
  themeId: string;
  claims: Record<string, string[]>;
  users: { id: string; name: string; role: string; color: string }[];
  getStatus: (name: string) => string;
  getPoints: (uid: string) => number;
  currentUser: string;
}

const STATUS_LABELS: Record<string, string> = { active: "LIVE", "in-progress": "BUILDING", planned: "PLANNED", concept: "CONCEPT" };
const PRIORITY_ORDER = ["NOW", "HIGH", "MEDIUM", "LOW"];

export type PDFResult = { ok: true } | { ok: false; error: string };

export function generatePipelineReport(opts: PDFOptions): PDFResult {
  try {
    return _generatePipelineReport(opts);
  } catch (err) {
    return { ok: false, error: (err as Error).message || "pdf generation failed" };
  }
}

function _generatePipelineReport(opts: PDFOptions): PDFResult {
  const { claims, users, getStatus, getPoints, currentUser } = opts;

  if (!pipelineData || pipelineData.length === 0) {
    return { ok: false, error: "no pipeline data to export" };
  }

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  const me = users.find(u => u.id === currentUser);
  const now = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  // Colors
  const dark = "#0d0a18";
  const accent = "#bf5af2";
  const green = "#00cc6a";
  const amber = "#cc9900";
  const textMain = "#f0ecff";
  const textDim = "#8880aa";

  // === PAGE 1: COVER ===
  doc.setFillColor(dark);
  doc.rect(0, 0, w, 297, "F");

  // Decorative lines
  doc.setDrawColor(accent);
  doc.setLineWidth(0.3);
  doc.line(20, 40, w - 20, 40);
  doc.line(20, 42, w - 20, 42);

  // Title
  doc.setTextColor(textDim);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("BINAYAH.AI", 20, 35);
  doc.text("CONFIDENTIAL", w - 20, 35, { align: "right" });

  doc.setTextColor(textMain);
  doc.setFontSize(36);
  doc.setFont("helvetica", "bold");
  doc.text("Pipeline Report", 20, 65);

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(accent);
  doc.text("Command Center Status Overview", 20, 75);

  doc.setTextColor(textDim);
  doc.setFontSize(10);
  doc.text(now, 20, 85);
  doc.text(`Generated by ${me?.name || "Team"}`, 20, 91);

  // Stats boxes
  const totalStages = pipelineData.flatMap(p => p.stages).length;
  const statusWeight: Record<string, number> = { concept: 0, planned: 25, "in-progress": 60, active: 100 };
  const overallPct = Math.round(pipelineData.flatMap(p => p.stages).reduce((sum, s) => sum + (statusWeight[getStatus(s)] || 0), 0) / totalStages);
  const claimedCount = Object.keys(claims).filter(k => (claims[k] || []).length > 0).length;

  const stats = [
    { label: "PIPELINES", value: String(pipelineData.length) },
    { label: "STAGES", value: String(totalStages) },
    { label: "PROGRESS", value: `${overallPct}%` },
    { label: "CLAIMED", value: `${claimedCount}/${totalStages}` },
  ];

  let sx = 20;
  const boxW = (w - 50) / 4;
  stats.forEach(s => {
    doc.setFillColor("#1a1530");
    doc.roundedRect(sx, 105, boxW, 28, 3, 3, "F");
    doc.setDrawColor(accent);
    doc.setLineWidth(0.2);
    doc.roundedRect(sx, 105, boxW, 28, 3, 3, "S");
    doc.setTextColor(accent);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text(s.value, sx + boxW / 2, 119, { align: "center" });
    doc.setTextColor(textDim);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text(s.label, sx + boxW / 2, 128, { align: "center" });
    sx += boxW + 3.3;
  });

  // Team section
  doc.setTextColor(textDim);
  doc.setFontSize(8);
  doc.text("TEAM", 20, 150);
  doc.setDrawColor(accent);
  doc.setLineWidth(0.2);
  doc.line(20, 152, w - 20, 152);

  users.forEach((u, i) => {
    const y = 158 + i * 10;
    doc.setFillColor(u.color);
    doc.circle(25, y, 2.5, "F");
    doc.setTextColor(textMain);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(u.name, 31, y + 1);
    doc.setTextColor(textDim);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(u.role, 60, y + 1);
    doc.setTextColor(amber);
    doc.text(`${getPoints(u.id)}pts`, w - 20, y + 1, { align: "right" });
  });

  // Bottom decorative
  doc.setDrawColor(accent);
  doc.setLineWidth(0.3);
  doc.line(20, 270, w - 20, 270);
  doc.setTextColor(textDim);
  doc.setFontSize(7);
  doc.text("BINAYAH.AI \u00B7 PIPELINE REPORT \u00B7 2026", w / 2, 278, { align: "center" });

  // === PAGE 2+: PIPELINE DETAILS ===
  const sorted = [...pipelineData].sort((a, b) => PRIORITY_ORDER.indexOf(a.priority) - PRIORITY_ORDER.indexOf(b.priority));

  sorted.forEach(p => {
    doc.addPage();
    doc.setFillColor(dark);
    doc.rect(0, 0, w, 297, "F");

    // Pipeline header
    doc.setTextColor(textDim);
    doc.setFontSize(8);
    doc.text(`${p.priority} PRIORITY`, 20, 18);
    doc.text(`${p.totalHours} \u00B7 ${p.points}pts`, w - 20, 18, { align: "right" });

    doc.setTextColor(textMain);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text(`${p.name}`, 20, 30);

    doc.setTextColor(textDim);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(p.desc, 20, 37);

    // Progress bar
    const pPct = Math.round(p.stages.reduce((sum, s) => sum + (statusWeight[getStatus(s)] || 0), 0) / p.stages.length);
    doc.setFillColor("#1a1530");
    doc.roundedRect(20, 42, w - 40, 4, 1.5, 1.5, "F");
    if (pPct > 0) {
      doc.setFillColor(accent);
      doc.roundedRect(20, 42, Math.max((w - 40) * pPct / 100, 3), 4, 1.5, 1.5, "F");
    }
    doc.setTextColor(accent);
    doc.setFontSize(8);
    doc.text(`${pPct}%`, w - 20, 41, { align: "right" });

    // Stages table
    const tableData = p.stages.map(s => {
      const status = getStatus(s);
      const claimers = (claims[s] || []).map(uid => users.find(u => u.id === uid)?.name || uid).join(", ");
      return [
        s,
        STATUS_LABELS[status] || status.toUpperCase(),
        String(stageDefaults[s]?.points || 0),
        claimers || "\u2014",
      ];
    });

    autoTable(doc, {
      startY: 50,
      head: [["STAGE", "STATUS", "PTS", "OWNERS"]],
      body: tableData,
      theme: "plain",
      styles: {
        fillColor: dark,
        textColor: [200, 195, 220],
        fontSize: 9,
        cellPadding: 4,
        lineColor: [40, 35, 60],
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: [26, 21, 48],
        textColor: [140, 130, 170],
        fontSize: 7,
        fontStyle: "bold",
        cellPadding: 3,
      },
      columnStyles: {
        0: { cellWidth: 60, fontStyle: "bold", textColor: [240, 236, 255] },
        1: { cellWidth: 25, halign: "center" },
        2: { cellWidth: 15, halign: "center", textColor: [204, 153, 0] },
        3: { cellWidth: "auto" },
      },
      didParseCell: (data) => {
        if (data.column.index === 1 && data.section === "body") {
          const val = data.cell.raw as string;
          if (val === "LIVE") data.cell.styles.textColor = [0, 204, 106];
          else if (val === "BUILDING") data.cell.styles.textColor = [204, 153, 0];
          else if (val === "PLANNED") data.cell.styles.textColor = [0, 180, 220];
          else data.cell.styles.textColor = [140, 130, 170];
        }
      },
    });

    // Footer
    doc.setDrawColor(accent);
    doc.setLineWidth(0.2);
    doc.line(20, 280, w - 20, 280);
    doc.setTextColor(textDim);
    doc.setFontSize(7);
    doc.text(`BINAYAH.AI \u00B7 ${p.name.toUpperCase()}`, 20, 287);
    doc.text(now, w - 20, 287, { align: "right" });
  });

  // Save
  doc.save(`binayah-pipeline-report-${new Date().toISOString().slice(0, 10)}.pdf`);
  return { ok: true };
}
